spring:
  application:
    name: news-curator
  datasource:
    # ../ 를 제거하여 프로젝트 루트 기준 collector/news.db 를 바라보도록 수정
    url: jdbc:sqlite:C:/Users/USER/IdeaProjects/news-curator/news.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate # 이미 파이썬 수집기가 테이블을 생성했으므로 검증만 수행
    show-sql: true
    properties:
      hibernate:
        format_sql: true